### ISSUE TITLE
"You have to mark exactly two elements..."

### ISSUE THREAD

**Issue by nilssinghof** [Steffen-W/KiCad-Parasitics#10]
Everything was working fine in the past, but for some reason I know always get the message "You have to mark exactly two elements..." even tough those two elements are already selected. Any idea what might be the cause? I have not changed anything

**Comment by Steffen-W** [comment]
Hi @nilssinghof ,

Maybe it's the same problem as in [issues/9](https://github.com/Steffen-W/KiCad-Parasitics/issues/9). If you have just installed kikit, I would uninstall it.

**Comment by nilssinghof** [comment]
Thanks, that worked out for me too!
