### ISSUE TITLE
checksum error while installing plugin

### ISSUE THREAD

**Issue by S-catKas** [Steffen-W/KiCad-Parasitics#13]
Also if I'm trying to install it with zip from github it says about the wrong metadata.json file.

**Comment by Steffen-W** [comment]
This is really very strange, as the version is very old. Can you give me more details about your kicad version and operating system? Which version did you try to install?

**Comment by S-catKas** [comment]
My KiCAD version is 8.0.1, 64-bit Windows 10.
It is really strange, because while I was looking for the plagin version I tried to install it again, and it was successful! So it works now, thanks for the development of this plagin :)
