### ISSUE TITLE
No information about "Probably no ngspice installation could be found"

### ISSUE THREAD

**Issue by F4HTB** [Steffen-W/KiCad-Parasitics#7]
Hi, 

Can you provide information about this error?

**Comment by Steffen-W** [comment]
Hi @F4HTB I need your kicad version, operating system and plugin version. If you are using MacOS I have to inform you that I have not implemented the connection to ngspice. But the error is usually not that bad, because a resistance should have been calculated before.

**Comment by F4HTB** [comment]
Hello dear, 

kicad version 7.0.6
operating system Windows 10 22H2
plugin version 2023.10.11

**Comment by Steffen-W** [comment]
@F4HTB please update to the latest version and test it again. It should be solved then.

**Comment by Steffen-W** [comment]
I am closing the issue as I assume that the problem has been solved.
